module: "src.tasks.OSInteraction"
parameters:
    name: "OS-Interaction-dev"
    match_problem: true
    check_problem: true
    round_limit: 8

    docker_config:
        localhost: local-os
        directory: data/os_interaction/res/dockerfiles

    scripts:
        directory: data/os_interaction/res/scripts

    data_config:
        files:
            - problem_file: data/os_interaction/data/dev.json
              script_dir: data/os_interaction/scripts/dev/

        bk: []
        ignore: []
