os_more_tasks = \
["Using bash command, create a new directory named 'Project1' inside ~/Documents directory. Then navigate into 'Project1' and create three new files named 'file1.txt', 'file2.txt', and 'file3.txt'.",
 "Create a bash script that checks the system's disk usage every hour. If the disk usage exceeds 90%, the script should send an email alert to the system administrator.",
 "Create a new user named 'new_user' and assign a password to it. Afterward, add this user to the sudo group to provide administrative privileges.",
 'Write a bash script that backs up a directory (say, ~/Documents) to a remote server using the rsync command. The script should only backup files that have been modified within the last 7 days.',
 "Create a bash script that monitors the system's CPU usage. If the CPU usage exceeds 75% for more than 2 minutes, the script should automatically kill the process consuming the most CPU power.",
 'Create a backup of all ".doc" files from the ~/Documents directory and its subdirectories to the ~/BackUp directory. Compress this backup into a zip file.',
 'Check the disk usage of the /var/log directory and its subdirectories. If it exceeds 1GB, clear all log files that were last modified more than 14 days ago.',
 "Create a script that will monitor the system's memory usage every 5 minutes. If the memory usage goes beyond 90%, it should send an alert email to the system administrator.",
 'Find all the duplicate files (by content not by name) in a certain directory and its subdirectories and move them to a separate folder.',
 'Monitor the /home/user/downloads directory and automatically unzip any .zip files that appear in the directory.',
 'Write a bash script that accepts text file names as arguments and counts the total number of lines in all the files combined. This is useful in case you want to compute the total number of lines in a group of text files.',
 'Assume you have a directory that contains many log files named in the format yyyy-MM-dd.log (e.g., 2022-03-08.log). Create a task to compress all log files into a zip that were created before a specific date.',
 'Create a task to monitor the disk usage of a particular directory and send an email alert if the usage exceeds a particular threshold.',
 'Create a task to find all the .mp3 files in a system, generate a list with the file path and size of these files and save the list as a text file.',
 "Write a bash script that checks if there are any processes running with more than 'X'% of CPU usage where 'X' is a parameter supplied to the script. If there are, the script should display the process IDs and the respective CPU usage. This can be useful for system administrators to monitor system performance.",
 'List all the running processes in the system. It should include the process ID, the command that started the process, and the current status of the process.',
 "Create a backup of all the files in your current directory that end in '.txt' into a new directory named 'backup'. ",
 "Monitor all the changes in the 'Documents' directory and write down these changes into a log file named 'doc_changes.log'. This should include all operations like file creation, deletion, modification, etc.",
 'Find all the files in your home directory that have been modified in the last 24 hours and sort them by the time of modification in descending order. ',
 'Find the total amount of disk space used and the available disk space in the system. The task should also calculate the percentage of disk space used.',
 'You have a large CSV file named "data.csv" containing transaction records. Each record contains a date within the format of YYYY-MM-DD. You need to extract all records of transactions that occurred in the year 2020.',
 'Compress all the files in your current directory that have the extension ".txt" into a tarball named "txt_files.tar".',
 'Calculate the combined size of all .jpg and .png files within a directory named "images" in your current directory. ',
 'Monitor a directory named "files" in your home directory and print a message whenever a file is added, removed, or modified within it.',
 'You have a directory named "projects", and you need to find out how many directories within "projects" have been modified within the last 7 days. This will help you understand which projects are actively being worked on.',
 "You have been asked to manage software packages on a Linux machine. Your task is to list all the installed packages on the system and save the output to a text file named 'package_list.txt'. Then, check if the 'apache2' package is installed on the system. If it isn't, install it.",
 "Suppose you want to find all the '.pdf' files in the 'Downloads' directory that contain the word 'linux'. Write a script to find these files and copy them to a new directory named 'Linux_PDFs' in your 'Documents' directory.",
 "You are required to automate the process of backing up certain directories on your system. Write a script that compresses the 'Documents' and 'Pictures' directories into a file named 'backup.tar.gz' and moves it to a directory named 'Backup' in your home directory.",
 "You are working on a project that involves a large number of text files. You want to find all the '.txt' files in your 'Projects' directory that were modified within the last 24 hours. Write a script that does this and saves the output to a file named 'recent_files.txt'.",
 "In a server environment, you want to keep track of your disk usage. Create a script that checks the amount of free space on your system every hour and saves the output in a log file named 'disk_usage.log' in the '/var/log' directory.",
 "The /var/log directory contains log files for the system and different services. Assume there is a log file called 'messages.log'. Your task is to print the entries of the last 5 days only.",
 "Assume there is a directory named 'Projects' in your home directory and it has multiple directories and files. Your task is to find the top 5 largest files in the 'Projects' directory and its subdirectories and display their size and path. ",
 "There is a CSV file named 'employees.csv' in your home directory which contains the data of employees. Your task is to display only the rows where the employee department is 'Marketing' and the salary is greater than 5000.",
 "Assume there is a directory named 'Scripts' in your home directory. Your task is to find all the shell script files (files ending with .sh) in the 'Scripts' directory and its subdirectories, and execute them.",
 "Suppose there is a text file named 'book.txt' in your home directory. Your task is to display the lines which contain the word 'Linux' and count the number of occurrences.",
 'In your current working directory, identify the longest line in terms of number of words in all .txt files.',
 'You have a directory named "photos" with numerous image files in .jpg format. Rename all the .jpg files in the directory by appending the current date at the end of each filename. ',
 'Find out the total number of CPU cores available in your Ubuntu system.',
 "You want to monitor the CPU and memory usage of your system every 5 minutes and save this information in a log file called 'system_monitor.log' ",
 'Create a directory structure where you have a main directory called "Projects" and under this directory, you have subdirectories named after the months (like "January", "February", etc.). In each of these subdirectories, create 4 more subdirectories named "Week1", "Week2", "Week3", and "Week4".',
 'You are tasked to create a backup of your current directory and all its subdirectories and files, compress it and store the backup in a directory named "backup" which is located in your home directory.',
 'Write a script to monitor the disk usage of your system. If the disk usage exceeds 80%, it should send an email to the system administrator with the details.',
 "Find all the PDF files in a directory named 'Documents' and convert them into text files with the same name but different extension (.txt) in a directory named 'TXTFiles'.",
 'Write a bash command to automatically update your system at a specific time every day. If updates aren\'t available, it should log a message into a file named "update.log" in your home directory.',
 'Write a script to check the status of a service (e.g. apache2). If the service is not running, the script should start the service and send an email notification to the system administrator.',
 'You need to automate the process of backing up all of your documents (".docx" files) weekly from your current working directory to a backup directory. Implement a bash script that does this and also logs any failures to a file named \'backup.log\' in your home directory.',
 "You have a file named 'attendance.csv' in your current directory, which contains the attendance record of your students. You recently received a list of students who have dropped the course. Your task is to read and remove all the dropped-out students’ records from the 'attendance.csv' file using bash shell commands.",
 'Your team uses a shared repository which is updated frequently. You want to keep the repository pulled at all times on your local system. Write a bash script to auto pull the updates from the repository every hour.',
 'You need to monitor a specific system process and log its resource usage (CPU, memory) every five minutes. The log file must be saved with the time stamp in its name.',
 'You are required to perform a system audit and need to gather all the system information, including the hostname, operating system, kernel version, uptime, and currently logged in users. Write a bash script to collect this information and save it to a text file.',
 'Monitor the performance of your system in real time by continually updating and displaying system statistics such as CPU usage, memory usage, swap usage, disk I/O, system load average and other performance metrics. ',
 "Find all files with .jpg extension in your home directory that were last modified more than 30 days ago, move them to a directory named 'old_images' in your home directory. If the directory doesn't exist, create it.",
 'Delete all empty directories within a given directory. This task should also include the deletion of directories that contain only empty directories.',
 'Check the availability of a specific domain in the internet, by pinging the domain every 5 minutes. If the domain becomes unavailable, write a log entry in a file named "domain_check.log" located in your home directory with the timestamp of when the domain became unavailable.',
 'Create a script that will backup a specified directory, compress the backup, and store it in another specified directory with the timestamp in the backup\'s filename. If the backup is successful, write a log entry in a file named "backup.log" located in your home directory with the timestamp of when the backup was created.',
 'You are required to monitor the disk usage of your system at regular intervals. The task is to write a cron job that runs a script every hour. This script should get the current disk usage using the `df` command and append it to a log file in your home directory.',
 'You have a directory named "photos" with numerous subdirectories, each containing several jpeg and png images. Your task here is to find all the png images that are above 1MB in size across all subdirectories of "photos" and move them to a new directory named "large_images" in your home directory.',
 'You have a "logs" directory that contains several log files. Your task is to find all the log files that have been modified in the last 7 days and archive them into a tar file named "recent_logs.tar".',
 "Your task is to write a script that checks if a particular process (let's say process_name) is running. If the process is not running, the script should start the process and send a mail notification to a given email address.",
 'You have a file named "data.txt" in your home directory. The file contains several lines of data. Each line in the file is a record and fields in the record are separated by commas. Your task is to use the `awk` command to print all records where the third field is greater than a certain value (let\'s say 100).',
 "Imagine a scenario where you have downloaded multiple software repositories in your '/home/downloads' directory. You need to identify which repositories are the largest ones. Write a command that lists all the directories and their respective sizes present in '/home/downloads' in decreasing order of their size.",
 "You have a huge collection of books in .pdf format, located in various subdirectories inside your 'books' directory. You may have duplicates and to save disk space, you want to find all the duplicate .pdf files. Write a command that finds and displays these duplicate .pdf files in your 'books' directory.",
 "Your 'Downloads' directory is quite cluttered with .zip files. You want to organize them by moving all the .zip files to a newly created directory named 'zip_files'. Write a command to create a new directory and move all .zip files from 'Downloads' to 'zip_files'.",
 "You have a script that generates a log file named 'output.log'. The script runs multiple times a day, and each time it runs, it appends the new logs to 'output.log'. The log file has grown quite large now, and you want to split the log file such that each file contains 1000 lines. Write a command that splits the 'output.log' file into multiple files, each containing 1000 lines.",
 'You have been working on a project and have made numerous changes to your files. However, you realize that you need to revert back to the state as it was 5 days ago. Assuming you have a backup directory where you copy your project files every day, write a command to copy the files from the backup directory as it was 5 days ago, to your project directory.',
 "Imagine that you need to keep track of all the modifications made to a specific directory, let's say '/home/user/documents'. Write a bash command that will list all the modified files within this directory for the last 24 hours.",
 "Occasionally, you need to share a directory with a colleague, but you would like to ensure that the files you are sharing do not contain sensitive information. Write a bash command that will search for files containing the word 'confidential' in the '/home/user/shared' directory.",
 "You have a directory containing numerous log files. You are tasked with archiving all '.log' files in this directory that haven't been modified in the last 7 days into a compressed tarball file.",
 "You are running an application that writes a large amount of temporary data to the '/tmp' directory. You notice that your disk usage is getting high, and you want to ensure that files in '/tmp' that are older than 30 days are removed.",
 "You have an outdated application installed on your system that you want to remove. However, you only remember the name partially, but you do remember it started with the letters 'gimp'. Using the bash command, list all the applications starting with 'gimp'.",
 'Write a bash command to create a backup of your current working directory and all of its subdirectories into a tar.gz file, with a timestamp in the filename, stored in your home directory.',
 'Create a bash script to monitor CPU usage. If the CPU usage exceeds 80%, an email should be sent to the system administrator with details of the processes utilizing high CPU.',
 'Write a bash script to automate the process of creating a new user on the system. The script should prompt for the username and password, create the user, and then create a personal directory for the user in /home/.',
 'Write a routine that checks disk space usage every 10 minutes. If the disk usage exceeds 90%, it should automatically clean the /tmp directory and free up space.',
 'Given a list of usernames in a text file, write a bash script that will check if each user exists on the system. If the user does not exist, the script should output a report with the usernames that could not be found.',
 "Given a CSV file named 'database.csv', filter out all the rows where the third column contains a value greater than 1000 and then write these rows to a new file named 'filtered.csv'.",
 "Given a directory named `archives`, compress all the files within this directory into a single tarball named 'backup.tar.gz' and then move this tarball to a directory named `backup`.",
 'Monitor continuously the CPU usage of a process with a given process ID (PID) and alert (print a message) if the CPU usage exceeds 50%.',
 'Find all the files in your system that were modified within the last 24 hours, then list these files along with their size and the time they were last modified.',
 "Given a directory named `logs`, go through all the `.log` files within this directory and find the lines where a specific IP address (e.g. '192.168.1.1') is mentioned, then write these lines to a new file named 'filtered_logs.txt'.",
 'Assume there is a file named "transactions.txt" in your current directory which contains a list of all transactions made by a company in the past month. Each transaction is recorded in a new line and the transaction amount is listed at the end of each line after a comma. You need to calculate the total sum of all transactions.',
 'In your current directory, there\'s a folder named "CustomerFiles" containing various customer information files. You are told to list all the .xml files in this directory which were modified in the last 7 days.',
 'Suppose you have a directory named `~/logs/` that contains numerous log files. You need to identify all the log files that were modified in the last 48 hours and move these files to another directory named `~/recent_logs/`.',
 'Given a directory named "Projects" in your home directory, some of the project directories inside it also have a directory named "config". You need to find all these config directories and create a tarball backup of these directories.',
 'In the directory `/var/www/html/`, you have multiple websites coded in HTML. Your task is to find and replace all instances of "http" with "https" for better security in all HTML files.',
 "Create a task to monitor the memory usage of your system every 5 minutes. If the memory usage exceeds 90%, the system should send an alert to the user's email.",
 'Set a task that periodically checks for system updates every week. If there are any available updates, the system should automatically download and install them.',
 'Create a bash script that will back up your entire home directory to an external drive or any other specified location at a given time every day.',
 'Write a bash script that can search for all occurrences of a specific word in all .txt files within a directory and replace them with a new specified word.',
 'Develop a script that will check the health of all services running on your system. If any service is found to be inactive, the script should try to restart the service and send a notification to the user.',
 'Create a function to monitor the disk usage of the `/var` directory. If it exceeds 50%, send an email to the system administrator with the report of the files and directories consuming most of the space.',
 'Set up a cron job to automatically back up the `/home` directory to an external storage device on every Friday at 10 PM.',
 'Write a script that checks the availability of updates for installed packages and automatically installs them if available.',
 'Design a function that verifies the integrity of all system files by comparing their current checksums with those at the time of their installation.',
 'Create a script that scans the `/var/log` directory and sends an alert if it finds any error logs that have been updated in the last 24 hours. This script should exclude informational or warning logs.',
 'Assume you have a complex project structure with numerous subdirectories and files. Your task is to locate and list all `.py` (python) files within the entire project structure starting from the current directory.',
 'You have a directory named `reports` that contains hundreds of files. You need to archive and compress this directory using the tar command and then move the compressed file to another directory named `backup`.',
 "You want to automate a task using a bash script. The task involves scanning through all the directories in the home directory, finding and deleting all temporary files ending with '.temp'.",
 "Assume a scenario where you have forgotten the location of a critical configuration file named 'app.config'. Your task is to locate this file in the system.",
 "You have been noticing some unusual activity on your system and suspect it's a particular process causing the issue. Your task is to find the process id of this process assuming the process name is 'mystery_process', and terminate it.",
 'You have to archive all the files in a directory named "documents" and then encrypt the resultant tar file with a password. ',
 'Schedule a task using Cron to automate the process of clearing system cache memory every week to optimize the performance of your Ubuntu system. ',
 'You have a directory named "videos". Calculate the total size of all .mp4 files in that directory and display in human-readable format.',
 "Write a Bash script that will monitor the availability of a website by pinging the website's IP address every 5 minutes. If the site is not reachable, the script should send an email notification. ",
 'Write a bash command to find all directories and sub-directories in your home directory where permissions are set to allow everyone to write, and change the permissions to only allow the owner to write.',
 'Automate the task of backing up your Documents directory to another location, for example an external hard drive mounted at /mnt/my_drive. Create a bash script that does this and can be run at any time.',
 'You are tasked to monitor the system resource usage of your linux machine. You will need to create a bash script that prints out the current CPU usage, memory usage and disk usage every 5 minutes.',
 "You have a directory named 'projects' which contains multiple subdirectories. Each subdirectory corresponds to different projects you have worked on, and each contains a file named 'project.txt'. You need to concatenate the contents of all 'project.txt' files into a single 'all_projects.txt' file.",
 'Create a bash script to automate the process of initiating a system update. The script should update the package list, upgrade all packages, and then clean up any unnecessary packages.',
 'You have a folder named "audio_files" filled with .mp3 files. Some of the files are named incorrectly. Write a script which can rename all .mp3 files according to a given pattern. For example, if the pattern is \'Track-Number\', rename the files to \'Track-1.mp3\', \'Track-2.mp3\' and so on.',
 'Monitor the CPU usage and memory usage of a specific process. If the usage exceeds a certain limit (say 80%), an email should be sent to the admin. This can be done using top and mail commands.',
 'Identify all the open ports and the services running on them for a specific IP address in the network. This can be done using nmap command.',
 "Compress all the files in the current directory which haven't been accessed in the last 30 days. This can be done using find, xargs, and tar commands.",
 'Find and delete all duplicate files in a directory. This can be done using fdupes command.',
 'Find out the total disk usage of a specific directory, for example, /home/username/Documents. The output should show the disk usage in human-readable format.',
 'Create a backup of all files in your current directory that have been modified in the last 24 hours. The backup should be a tar.gz file named "modified_files.tar.gz".',
 'List all USB devices connected to your system. The output should include the device name, manufacturer, and serial number.',
 'Create a new user with a home directory, but without shell access. This could be useful for creating a user for file sharing purposes.',
 'Find and kill a process that is using a particular port, for example, port 8080. This could be useful if a server process has become stuck and is preventing a new server process from starting.',
 'Create a cron job that automatically backs up your /home/user/documents directory to /home/user/backup every Sunday at 3:00 AM.',
 'Monitor the memory usage of a particular process, say "mysqld", using the \'top\' command and write the output into a log file in your home directory every 2 hours.',
 'Find all the files in your /home/user/downloads directory that have been downloaded but have not been accessed for the last 30 days, and move them to a directory called /home/user/archive.',
 'Identify and list all the directories and subdirectories in your /home directory that has files of size more than 1GB.',
 'Write a script that will check the disk usage of your /home directory every hour. If disk usage exceeds 90%, automatically delete files in /home/user/temp that are older than 7 days.',
 'Create a shell script that asks user for a text input, searches this input as a string in all the .txt files in the current directory, and if found, outputs the name of the file and the line number where the string occurs.',
 "Write a script that finds the top three directories consuming the most disk space in the '/home' directory. The script should display the directory path and the space it is consuming.",
 "Write a script that backs up all files in the current directory that were modified within the last 24 hours to a directory named 'backup'. If the 'backup' directory doesn't exist, the script should create it.",
 "Write a script that monitors the memory usage of a particular process, say 'MyProcess'. If the memory usage of 'MyProcess' exceeds 1 GB, the script should alert the user by outputting a message to the console.",
 'Write a script that checks the availability of updates for installed packages and automatically installs them, if updates are available. The script should also log the details of installed updates along with the timestamp.',
 "Within a directory named 'projects', find and list all '.java' files that were modified in the last 7 days. Also, count how many such files exist.",
 "From the log file '/var/log/syslog', find all the lines that contain the word 'error'. Extract the date and time of each error and save them in a separate file named 'error_timestamps.txt'.",
 'Suppose you have a file `employee_data.csv` where each line represents data for an employee in the following format: "Name, Designation, Age, Salary". Write a script to find the average salary of all the employees.',
 "In your current directory, find all '.txt' files and replace the word 'Linux' with 'Ubuntu' in each of these files.",
 'Write a script to monitor the disk usage of your current directory. If the disk usage exceeds 1GB, send an email notification to the user warning them about the disk space.',
 'Compress all PDF files in your Documents directory into a single .zip file, and then move this .zip file to your Desktop directory.',
 'Calculate the total size of all .log files in the /var/log directory. The size should be displayed in human-readable format (e.g., KB, MB, GB).',
 'List all processes running by a particular user, say "JohnDoe", and save this list to a text file in your home directory.',
 'From your home directory, recursively search for all .mp3 files, then convert the encoding of these files from ISO-8859-1 to UTF-8 without changing their original contents.',
 'Monitor the CPU and memory usage of your Linux system every five seconds, and if either the CPU or memory usage exceeds 80%, send an email alert to a specified email address.',
 'Extract all email addresses from a specified .txt file and save them in a new file called "email_addresses.txt".',
 "Find out the number of occurrences of the word 'error' in all .log files under /var/log directory.",
 'List out all the directories in the /home directory that are currently empty.',
 'Create a new user named "temp_user", set a password for this user and then assign it to the "sudo" group.',
 'Archive and compress all .jpg and .png files in the Pictures directory into a tar.gz file named "images.tar.gz".',
 'Create a backup of all your documents from "Documents" folder into a new folder named "BackupDocuments" in your home directory, and then archive and compress this backup folder using tar and gzip commands.',
 'Write a bash script to monitor the disk usage of your home directory. If the disk usage goes beyond 80%, the script should send an alert email to your registered email id.',
 "Use a Linux command to find out the total number of processes running for a specific user like 'john'. ",
 'Write a bash script which checks for the availability of all installed packages updates in the system and list them. If updates are available, the script should update those packages automatically.',
 "Write a bash script to check for the system's CPU usage. If the CPU usage exceeds 75%, then the script should kill the processes consuming the most CPU usage to prevent the system from becoming unresponsive.",
 'Rename all .jpg files in a directory to .png using a single bash command.',
 'Monitor and report the memory usage every 5 seconds until manually stopped.',
 'Create a new user account, set a password for it, and grant it sudo privileges.',
 'Create a cron job that will automatically clean the trash bin every week.',
 "Write a command to monitor a text file named 'logfile.txt' in real-time. Your task is to print any new lines added to this file instantly as they are written to the file.",
 'You want to install a new software package but you are not sure if you have enough disk space left. Write a command to check the available disk space on your system.',
 'The user should be able to list all the installed software packages in the system along with their version numbers. The list should be sorted in descending order of the date they were installed on.',
 'The user has a large number of .jpg files in a directory "images". The user needs to rename all .jpg files in the format "image_x.jpg" where x is an incrementing number starting from 1. Additionally, user also needs to create a log file logging the original file name and the new file name.',
 'The user has a folder named "docs" which contains several .docx files. The user needs to figure out the number of files that contain a specific word "Linux". Additionally, the user also needs to create a text file named "output.txt", listing the names of those files along with the number of occurrences of the word "Linux".',
 'Create a task that identifies all the directories in the /home/ directory that have been modified within the last 7 days.',
 'In your current directory, count how many image files (jpg, png, gif) have a resolution higher than 1920x1080 pixels.',
 'Find out how many files in the /usr/local/bin directory have the execute permissions set for all users.',
 "Assume that you have various types of files (e.g., '.txt', '.pdf', '.jpg') in your Documents directory. Write a command to move all '.jpg' files from the Documents directory to a new directory named 'Images' in your home directory.",
 "Assume you have a directory called 'Logs' which is filled with multiple log files. Your task is to find all the log files which have been modified in the last two days.",
 "A file named 'data.txt' in your home directory contains thousands of lines of data. Create a command to display the first 10 lines of the file, and the last 10 lines of the file, simultaneously.",
 "You are in a directory named 'scripts' that contains various bash scripts (.sh files). Write a command to identify and display only those script files which were last modified more than 30 days ago.",
 "You have a directory named 'work' containing various sub-directories and files. Your task is to find all the files with the extension '.docx' that were created or modified within the last 7 days and display the count.",
 "You are in a directory named 'projects', which consists of various project sub-directories. Each project directory contains a '.info' file with project details such as the project name, description, and the name of the project lead. You need to write a command to extract the project lead's names from all the '.info' files and sort them alphabetically.",
 'Your task is to find all the files in your documents directory that were modified within the last 7 days and compress them into a zip file named "recent_files.zip".',
 "You need to monitor the system's memory usage every 5 minutes. If the memory usage exceeds 70%, a warning message should be sent to the system administrator.",
 "There is a directory named 'Projects' which contains several subdirectories for each project. Each subdirectory has a log file named 'project.log'. You have to find the project log file which contains the word 'ERROR' the maximum number of times. Display the name of the project and the count of 'ERROR'.",
 'Set up a cron job that runs a script to back up a specific directory to an external hard drive every Sunday at 3am.',
 'Count the number of files in your home directory that were modified more than 30 days ago.',
 'Using a bash command, find the top three processes consuming the most CPU resources on your system.',
 "You have a directory named 'project' which contains multiple sub-directories and files. Your task is to find out the total number of PDF files present in all these sub-directories. ",
 "You are required to list all the empty directories in your 'Documents' folder in a file named 'empty.txt'. ",
 'Assume you are running multiple applications on your Linux operating system. Your task is to find out the memory usage of each application and list down the applications using more than 100MB memory.',
 "You are given a directory named 'documents'. This directory contains numerous subdirectories and files. Your task is to find all PDF files in the 'documents' directory and its subdirectories that were modified within the last 30 days. ",
 "A files named 'users.txt' in your home directory contains a list of all usernames on your system, one username per line. Your task is to create a new group called 'developers' and add all the users from this file to that group.",
 'The Linux system you are working on has multiple network interfaces. Your task is to identify the network interface that has been used to send the greatest amount of data.',
 'Assume there is a directory named `logs` in the home directory. This directory contains multiple log files of various applications. Write a bash command that will recursively search through the "logs" directory and delete all log files that have not been modified in the last 60 days.',
 "There are multiple directories in the current directory, each directory is named after a date in the format 'YYYY-MM-DD'. Write a task to list all directories that were created in the year 2020.",
 "In your home directory, there is a text file named 'contacts.txt'. This file contains names, phone numbers and email addresses of various contacts. Each line represents a single contact and the fields are separated by commas. Write a task to list the email addresses of all contacts whose name starts with 'John'. Also, count the total number of such contacts.",
 "You're asked to monitor a specific process with process ID 1234. Write a script to monitor the CPU and Memory usage of this process and write the data into a log file named 'process_monitor.log' every 5 seconds.",
 "Your manager wants to know the top 10 largest files (in terms of file size) in the '/var/log' directory of your Linux system. Generate a list of these files along with their size information.",
 "You have a large directory tree in your Linux system under the '/home/user/data' directory. You are asked to find out the total number of '.jpg' and '.png' image files present in this directory tree.",
 'Create a script to compress all the .jpg files in the "Pictures" directory in your home folder into a single zip file named "pictures_archive.zip" and move it to a directory named "Archives". ',
 "Write a shell script that will rename all .txt files in your home directory and its subdirectories with a '_old' suffix. ",
 'Monitor the \'Downloads\' directory and create a log entry in a file named "download.log" each time a file is added. The log entry should contain the filename and the timestamp of when the file was added.',
 "You have to organize your Mp3 music collection. Rename all the mp3 files in the Music directory such that they follow the format 'artistName_songName.mp3'. Assume that the current file names have artist and song name separated by a hyphen(-).",
 "From the directory /var/logs/apache2, count how many times the HTTP status code '404' appears in the access.log file of yesterday's date.",
 "There is a folder named 'Projects' in the home directory which contains many subdirectories for different projects. Get the list of subdirectories which have not been modified in the last 30 days.",
 'Monitor the system resource usage continuously. Specifically, display the CPU usage, memory usage, swap usage, and disk I/O statistics every 5 seconds.',
 'Your task is to find out the list of all files with .txt extension, modified within the last week, and then sort them by the date of modification (from newest to oldest) in your home directory and its subdirectories.',
 'Your task is to create an organized list of all installed packages on your Linux system, sorted alphabetically, and then write this list into a text file. Make sure that the file is located in your home directory.',
 'You have a directory named `logs` which contains multiple log files from different days of the month. Your task is to write a bash command that will compress all log files that were last modified more than a week ago into a single zip archive.',
 "Suppose you have a project directory with various subdirectories and files in it. Your task is to create a bash script that will find all .cpp and .h files in the directory and its subdirectories and replace all occurrences of the word 'foo' with 'bar' in these files.",
 'Monitor the network traffic on your machine for a specific period of time (for example, 30 minutes) and report which IP address made the most number of connections to your machine during that period.',
 "Given a directory named 'Project' in your home directory, create a list of all files within this directory and its subdirectories that were modified within the last 7 days. ",
 "Imagine you have a file named 'data.txt' stored in multiple directories and subdirectories on your system. Write a command which will find all these files and replace the word 'linux' with 'ubuntu' in every file. ",
 'Create a task to find all the files in the "/var/log" directory that were updated within the last 24 hours, and include the file\'s size in megabytes and the last modified date and time in the output.',
 'Write a command sequence that will display the top three largest files from the "/usr/bin" directory. The output should include files\' path, size, and the last access time.',
 'Create a task to locate all the hidden files within your home directory, exclude the directories, and calculate the total number of these hidden files. The result should only display the counts of such files.',
 'Write a bash script that checks the status of a service (like Apache or MySQL) every 30 minutes. If the service has stopped, it should automatically restart it and send an email notification to a specified address.',
 'Given a directory named `project_files`, find all the files with `.py` extension that were modified in the last seven days and move them to a separate directory named `recently_modified_python_files`.',
 'Create a Bash script that, on a daily basis, checks for disk space usage on your system. If the usage is more than 85%, it should send an email alert to a specific user.',
 'Create a bash script named "user_analysis.sh", that reads a list of usernames from a text file "users.txt" and checks whether these users exist in the system or not. The script should output the usernames that do not exist in the system.',
 'Write a bash script that checks for .log files in a directory /var/logs and compresses them if they are larger than 100MB. After compressing, the original .log file should be deleted.',
 'You are required to write a script named "cron_backup.sh" that creates a backup of the /home directory every midnight. The backup should be stored in /backups and each backup should be saved in a directory named with the current date in YYYY-MM-DD format.',
 'Write a script to monitor a specific directory for the creation of .tmp files. Whenever a .tmp file is created, the script should email the system administrator.',
 'Imagine you have the log files of a server saved in a directory. Write a command to find all the log files which have been modified in the last 24 hours and contain the word "ERROR".',
 'Assume you have a list of users in a text file. Write a bash command to create a new group, add these users to that new group, and then assign read and write access to a specified directory for this new group.',
 "A system administrator is interested in monitoring the system's memory usage. For this, he needs to write a script that checks and prints the total amount of used and free memory in the system every 5 minutes.",
 'You are asked to analyze the logs of a server. The logs are stored in a file named "serverlogs.txt" and you need to find out all the unique IP addresses that made a request to the server in the past 24 hours.',
 'Write a script that will list down all the running processes in the system, sort them by CPU usage in descending order and then write the output to a file named "processes.txt".',
 'Display the top 5 directories in your home directory consuming the most disk space. You need to recursively calculate the size of each directory including its subdirectories.',
 'Write a bash script that will monitor overall CPU usage over a 24 hour period on your system and save the results to a text file, with a new entry every hour. Remember to include the time stamp with each entry.',
 'Compress all .txt files in your documents directory that were modified within the last 2 days into a tar.gz archive. List the files that will be included in the archive before creating it.',
 'Create a bash script that will list out the top 5 directories consuming the most disk space in your Linux OS. ',
 'Develop a task that monitors the CPU utilization of your system every 10 seconds and displays a warning message if the CPU usage exceeds 80% continuously for more than a minute. ',
 'Formulate a task to verify the integrity of files in a directory by creating a checksum for each file and later use these checksums to detect if any file has been altered.',
 'List out all the files in your current directory which have been modified in the last 10 days and that the user has read permissions to.',
 "Archive all the directories in your home folder that are more than 1GB in size, excluding the 'Downloads' directory.",
 'Write a script that checks if the disk space of your system is more than 85% full. If it is, send an email to the system administrator.',
 "You are responsible for auditing system usage on a Linux server. You need to find out how long each user has been logged into the system. Generate a report that lists each user's login time and total usage time in hours.",
 "You are an administrator who needs to assess disk usage on your Linux server. Retrieve file size information in human-readable format (Kilobytes, Megabytes, Gigabytes) and list down those files only which sizes are greater than 1 Gigabyte from the '/home' directory.",
 'You are managing a server and want to ensure its security. Write a command to scan and list all the SUID (Set User ID) and SGID (Set Group ID) files for potential security risks in your system.']