module: "src.agents.api_agents.OpenAIChatCompletion"
parameters:
    name: "gpt-3.5-turbo"
    api_args:
        model: "gpt-3.5-turbo"
        # key: <assign your openai key here>
        # base: <assign your openai base here>
        timeout: 120
