docker_image: "localhost/task:mind2web"
module: "src.tasks.Mind2Web"
parameters:
    name: "Mind2Web-dev"
    data:
        data_path: "."
        cache_path: "./data/mind2web/.cache/data"
        test_split_files:
            test_domain: /root/work/data/data_dev/*.json
        score_file: /root/work/data/scores_all_data.pkl
    train:
        neg_ratio: 0.2
        num_candidates: 5
        max_context_len: 512
    model:
        mode: "multichoice"
        name: flan-t5-base
        model_name_or_path: "google/flan-t5-base"
        max_seq_length: 2048
    eval:
        topk: 10
    seed: 123
    llm_prompt: data/mind2web/prompt/llm_prompt_cot.json
